### ISSUE TITLE
Is not working with N2

### ISSUE THREAD

**Issue by bromic1** [jfath/RPi.GPIO-Odroid#5]
The library is not working with N2. Is there a way?

Traceback (most recent call last):
  File "simplerw.py", line 4, in <module>
    import RPi.GPIO as GPIO
  File "/usr/local/lib/python2.7/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!

**Comment by jfath** [comment]
Thanks - I don't own a N2, so no way to test.

**Comment by dikokob** [comment]
I have the same issue, have you had any luck?

**Comment by vadimsavitskii** [comment]
Any updates?
